# Generated by Django 6.0.3 on 2026-03-22 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='title',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='score',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
        migrations.AddField(
            model_name='assignment',
            name='is_submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mark',
            name='external_marks',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mark',
            name='internal_marks',
            field=models.IntegerField(default=0),
        ),
    ]
