# Generated by Django 6.0.3 on 2026-03-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_remove_assignment_status_remove_assignment_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='external_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='mark',
            name='internal_marks',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
